#!/usr/bin/env bash

# UDEV rules for setting backlight PWM frequency on Intel HD Graphics
# http://devbraindom.blogspot.com/2013/03/eliminate-led-screen-flicker-with-intel.html

# Dependencies:
# - intel-gpu-tools

# Sahri Riza Umami
#   v0.1 - 2020-05-05 19:57:11
#        - Initial release
#
# LICENSE ----------------------------------------------------------------------
#
# This is free and unencumbered software released into the public domain.
#
# Anyone is free to copy, modify, publish, use, compile, sell, or
# distribute this software, either in source code form or as a compiled
# binary, for any purpose, commercial or non-commercial, and by any
# means.
#
# In jurisdictions that recognize copyright laws, the author or authors
# of this software dedicate any and all copyright interest in the
# software to the public domain. We make this dedication for the benefit
# of the public at large and to the detriment of our heirs and
# successors. We intend this dedication to be an overt act of
# relinquishment in perpetuity of all present and future rights to this
# software under copyright law.
#
# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND,
# EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF
# MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT.
# IN NO EVENT SHALL THE AUTHORS BE LIABLE FOR ANY CLAIM, DAMAGES OR
# OTHER LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE,
# ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR
# OTHER DEALINGS IN THE SOFTWARE.
#
# For more information, please refer to <http://unlicense.org>
#
# ------------------------------------------------------------------------------

# VARIABLES --------------------------------------------------------------------

SCRIPT='/usr/bin/intelpwm'

udev_rules='KERNEL!="intel_backlight", SUBSYSTEM!="backlight", ACTION!="change", GOTO="backlight_pwm_rules_end"

RUN="/usr/bin/intelpwm"

LABEL="backlight_pwm_rules_end"
'

intelpwm_script='#!/usr/bin/env bash

PERIOD=65C
RAWDATA="$(intel_reg read 0xc8254)"
CYCLE="${RAWDATA:56:4}"

intel_reg write "0xc8254" "0x${PERIOD}${CYCLE}"
'

# FUNCTIONS --------------------------------------------------------------------

reload_udev() {
  sudo udevadm control --reload-rules
}

install_intelpwm() {
  echo "$udev_rules" | sudo tee -a /usr/lib/udev/rules.d/99-intelpwm.rules > /dev/null
  sudo chmod 644 /usr/lib/udev/rules.d/99-intelpwm.rules
  echo "$intelpwm_script" | sudo tee -a $SCRIPT > /dev/null
  sudo chmod 744 $SCRIPT
  reload_udev
  echo "${0##*/} has been installed."
}

remove_intelpwm() {
  sudo rm /usr/lib/udev/rules.d/99-intelpwm.rules $SCRIPT
  reload_udev
  echo "${0##*/} has been removed."
}

print_usage() {
  printf '%s\n' "
  ${0##*/} is UDEV rules for setting backlight PWM frequency on
  Intel HD Graphics.

  Usage: ${0##*/} OPTION

  OPTION:
    -h  --help      Show this message and exit
    -c  --check     Check values from intel_reg and $SCRIPT
    -e  --edit      Edit $SCRIPT
    -i  --install   Install udev rules
    -rm --remove    Remove udev rules
    -r  --reload    Reload udev
"
  exit
}

# MAIN -------------------------------------------------------------------------

[[ "$#" -ne 1 ]] && print_usage

# Checking dependenciy
if [[ -z $(command -v intel_reg) ]]; then
  echo 'intel-gpu-tools not found!'
  exit
fi

case "$1" in
  -c|--check)
    if [[ -e $SCRIPT ]]; then
      echo "PERIOD value set in script: $(awk -F= '/PERIOD/ {print $2}' $SCRIPT)"
      sudo intel_reg read 0xc8254 | awk '{sub(/^/, "")};1'
      sudo intel_reg read 0xc6204 | awk '{sub(/^/, "")};1'
    else
      echo "${0##*/} is not installed."
    fi
  ;;
  -e|--edit)
    sudo nano "$SCRIPT"
  ;;
  -i|--install)
    install_intelpwm
  ;;
  -rm|--remove)
    remove_intelpwm
  ;;
  -r|--reload)
    reload_udev
  ;;
  -h|--help|*)
    print_usage
  ;;
esac
